version: '3.8'

services:
  tea-store:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
    environment:
      - JWT_SECRET=${JWT_SECRET}

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_data:
